# Importing the random module.
import random


# Generating a random number between 1 and 15.
limit = 15
#random.seed(100)
number = random.randint(1,limit)

print(number)



# This is a while loop that is asking the user to input a number and then it is checking if the number
# is less than the number generated by the computer. If the number is less than the number generated
# by the computer, it will print out a message to the user. If the number is greater than the number
# generated by the computer, it will print out a message to the user. If the number is equal to the
# number generated by the computer, it will break out of the loop.
with open('Py_Projects/test.txt', 'a+') as test_file:
    # This is asking the user to input his/her name and then printing out a message to the user.
    player_name = input("Hello what is your name ? ")
    number_of_guesses = 0
    print('okay! ' + player_name + ' I am  guessing a number between 1 and ' + str(limit))
    
    while number_of_guesses < 5:
        guess = int(input())
        number_of_guesses +=1
        if guess < number:
            print("Your guess is too low.")
        if guess > number:
            print("Your guess is too high.")
        if guess == number:
            break
        
    # This is an if statement that is checking if the number guessed by the user is equal to the number
    # generated by the computer. If the number guessed by the user is equal to the number generated by the
    # computer, it will print out a message to the user. If the number guessed by the user is equal to the
    # number generated by the computer and the number of guesses is equal to 1, it will print out a
    # message to the user. If the number guessed by the user is not equal to the number generated by the
    # computer, it will print out a message to the user.
    if guess == number:
        print("You have guessed the number in " + str(number_of_guesses) + " tries")
    elif guess == number and number_of_guesses ==1:
        print("You have guessed the number in " + str(number_of_guesses) + " try! WELDONE")
    else:
        print("You did not guess the number, The number was " + str(number))    

    test_file.write(f"The player name is {player_name}, It took {str(number_of_guesses)} guesses\n")
    